services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3010:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s/"
    volumes:
      - /opt/infra-grafana/config/provisioning:/etc/grafana/provisioning:ro
      - /opt/infra-grafana/config/dashboards:/var/lib/grafana/dashboards:ro
      - grafana_data:/var/lib/grafana
      - ./config/provisioning:/etc/grafana/provisioning:ro
      - ./config/dashboards:/var/lib/grafana/dashboards:ro

volumes:
  grafana_data:
