events {}

http {
  server {
    listen 8080;

    # Allow ONLY edge-router
    allow 192.168.1.71;
    deny all;

    location /healthz {
      proxy_pass http://ingest-gateway:8080/healthz;
    }

    location /ingest {
      proxy_pass http://ingest-gateway:8080/ingest;
    }
  }
}
